title: spacekey.dev
google_analytics: UA-201413849-1
future: false

defaults:
  - scope:
      path: ""
    values:
      image: /assets/logo_icon_128.png

twitter:
  card:             "summary"
  username:         "dlspacekey"

gems:
  - jekyll-sitemap
  - jekyll-feed
